### ISSUE TITLE
Getting "unable to configure handler 'info_file_handler'" error

### ISSUE THREAD

**Issue by hepbc** [weihesdlegend/Auto-complete-System#5]
Hi, am new to server-side coding. I have done the following:
1. Routine install of Anaconda. Did not edit any path variables
2. pip install py2neo
3. Change dir to directory where this code is
4. Ran python app.py from cmd prompt
5. Gives me the above error: Unable to configure handler 'info_file_handler'
Is this a path issue? Would appreciate your help.

For reference:
Anaconda installed in E:\Anaconda
This code downloaded in E:\codes\Autocomplete

Thanks

**Comment by weihesdlegend** [comment]
Can you please provide more error message?

**Comment by hepbc** [comment]
Thanks for your response Weihe, reproducing the full error here:

(base) E:\codes\Autocomplete>python app.py
Traceback (most recent call last):
  File "E:\Anaconda\lib\logging\config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
  File "E:\Anaconda\lib\logging\config.py", line 735, in configure_handler
    result = factory(**kwargs)
  File "E:\Anaconda\lib\logging\handlers.py", line 147, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "E:\Anaconda\lib\logging\handlers.py", line 54, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "E:\Anaconda\lib\logging\__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "E:\Anaconda\lib\logging\__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\codes\\Autocomplete\\log_files\\db_update_info.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 47, in <module>
    app = Application(root)
  File "app.py", line 14, in __init__
    self.app = Server()
  File "E:\codes\Autocomplete\src\Server.py", line 61, in __init__
    logging.config.dictConfig(config)
  File "E:\Anaconda\lib\logging\config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "E:\Anaconda\lib\logging\config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'info_file_handler'

(base) E:\codes\Autocomplete>

**Comment by weihesdlegend** [comment]
Hi @hepbc , thanks for the complete error message. I was able to reproduce the issue today. It is indeed a bug if people just clone the repo and try to run app.py! 
The issue is there is no such file as log_files/db_update_info.log. For now please manually create the file and try to run the command "python app.py" again. I verified with Python 3.6 and it should work. Also please make sure you have Neo4j database up and running locally. 
I will make a commit to fix the issue soon.

**Comment by weihesdlegend** [comment]
issue resolved. Check latest version.
